
## Configuration

Podman requires you to create a virtual machine with user-specified characteristics *before* you can run an image. You can think of this as specifying the 'hardware' of the computer before you buy it (How much RAM? How big a hard drive? And so on.). In principle, this means that you can have more than one valid configuration at a time which would allow you to tune each virtual machine to your needs (one machine could have a lot of memory, another a lot of storage). You can read a more detailed explanation of [how to configure a virtual machine](./configuring.qmd), but below is the 'quick start' version.

::: {.panel-tabset}

### Apple MacOS

In the Terminal you simply:
```bash
podman machine init
podman machine start
```

### Windows

In the PowerShell or Window Terminal you *should* be able to simply:
```bash
podman machine init
podman machine start
```

::: {.callout-tip}
### Unable to Run

In a small number of cases we've need to create a new, named virtual machine (e.g. `podman machine init myvm`) and then change the default. Hopefully this isn't going to be needed.

:::

:::
