---
title: "Code Camp"
author: "Jon Reades"
date: "7/14/2025"
---

**Code Camp** provides a gentle introduction to the basics of programming in Python. Across about twelve sessions you will learn about syntax, variables, 'simple' data structures such as lists and dictionaries, and about the fundamentals of writing functions for reusable code. The sessions are entirely self-led: you should follow along at your own pace and remember that 'it's a marathon, not a sprint'.

We've tried to keep Code Camp as simple as possible so that you can get started as quickly as possible. We recommend that you simply [run Code Camp in your browser](https://jreades.github.io/code-camp/setup/no_install.html#in-your-browser) since that will allow you to learn (and run) Python anywhere and any time. However, you are welcome to run Code Camp code on your own computer (see: [install options](https://jreades.github.io/code-camp/setup/install.html)).

## TL;DR

Just point your browser to [Lesson 1](https://jreades.github.io/code-camp/lessons/Introduction.html) and get started because there's nothing to install.

