---
title: "Preparation"
author: "Jon Reades"
date: "8/11/2025"
---

Over the years, we have experimented with a range of approaches to setting you up with a programming environment, and we have come to the conclusion that **Podman**^[And Docker, which is basically the same thing.] is the most robust way to ensure a consistent experience. This guarantees that all students end up with the same versions of each library, that difficult-to-diagnose hardware/OS issues are minimised, and that running/recovery is the most straightforward.

::: {.callout-important}
## Base Utilities

Before beginning *any* of the steps below, make sure you have installed the [Base Utilities](../req/base.qmd) for your Operating System and checked the other hardware and software requirements.

:::

{{< include _downloading.qmd >}}

{{< include ./_installing.qmd >}}

{{< include ./_running.qmd >}}

{{< include ./_success.qmd >}}

## When Things Go Wrong

If you encounter any problems with the installation, please have a look at the [Dealing with Docker Problems](../docker/problems.qmd) page.
