---
title: "Requirements"
author: "Jon Reades"
date: "8/11/2025"
---

This guide will help you to perform a basic 'health check' on your computer to see if you're likely to run into problems running the programming environment. When answering the questions below, 'your computer' is the machine on which you plan to do the programming.

::: {.callout-tip}
### TL;DR

If your computer is less than 4 years old, has plenty of RAM and more than 20GB of free disk space then you're *probably* fine. The only other common issue is pif you have Windows 10 *Home* installed.

::: 

We try to support as many different configurations as possible, but there is *no* programming environment that installs and runs seamlessly on *all* computers so if you run into issues please come back to this guide.

## Hardware Requirements

In our experience the students **most likely to encounter problems** share one or more of the following:

1. Your computer 8GB or less of RAM.
2. Your computer has less than 20GB of free disk space remaining.

Read on below to check what specification you have...

::: {.panel-tabset}

## MacOS

You will need to look up:

- How much RAM does _your computer_ have? [Help for Mac](https://www.macworld.co.uk/how-to/mac/much-ram-need-more-3793418/).
- How much free disk space does _your computer_ have? [Help for Mac](https://www.macworld.com/article/2972775/how-to-check-a-mac-free-hard-drive-space.html).

## Windows

You will need to look up:

- How much RAM does _your computer_ have? [Help for Windows](https://www.howtogeek.com/435644how-to-see-how-much-ram-is-in-your-pc-and-its-speed/).
- How much free disk space does _your computer_ have? [Help for Windows](https://www.lifewire.com/how-to-check-free-hard-drive-space-in-windows-2619187).

## Linux

We're going to assume that you know what you're doing. If you want a recommendation, we'd probably go with the latest Ubuntu desktop release.

:::

If your computer has less than 8GB of RAM *and/or* less than 20GB of free disk space you are likely to have issues with [virutalisation](virtualisation.qmd) and (on Windows) WSL2. Your options are: 1) add more RAM (possible on Windows); 2) back up and remove unnecessary files (Movies, Photos, and Applications are particularly big 'hogs').

## Software Requirements

In our experience the students **most likely to encounter problems** share one or more of the following:

1. Your computer runs Windows 10 Home or older, or 
2. Your computer runs MacOS 10.13 (High Sierra) or older.

As long as your computer is running one of the last two major releases of the Operating System you should encounter few issues.

::: {.panel-tabset}

### MacOS

You will need to look up:

- What Operating System and Version is _your computer_ running? [Help for Mac](https://support.apple.com/en-gb/HT201260).

### Windows

You will need to look up:

- What Operating System and Version is _your computer_ running? [Help for Windows](https://support.microsoft.com/en-gb/help/13443/windows-which-version-am-i-running).

:::

### Recommendations

If you are using a Mac then your system should have the option to update to the latest version of the MacOS at no charge. If you are unable to update then it is likely that you have an older machine that is not fully supported by the most recent Operating System and, in all probability, you will also encounter issues running the programming environment.

If you are using a Windows PC then try to update to either Windows 11 or to Windows 10 Pro as this will 'unlock' additional features that are useful for supporting the programming environment. As a student you are likely to qualify for significantly cheaper/free updates, so make sure you do this when you have access to a discount.


